### ISSUE TITLE
Add equipment management to the app and link to rooms

### ISSUE THREAD

**Issue by stewnight** [stewnight/legacy-grow-app#58]
Add equipment to the schema and new tab, then a special tap in the rooms

**Comment by stewnight** [comment]
Here's the plan:
### Milestones for Equipment Management (#58)

1. Schema and Type Definitions

- [ ] Create equipment schema with proper relations
- [ ] Define equipment types and status enums
- [ ] Add equipment metadata interface
- [ ] Set up equipment-room relationships

2. Equipment List View

- [ ] Create equipment landing page
- [ ] Implement DataTable with filters
- [ ] Add create/edit forms
- [ ] Include basic search and filtering

3. Equipment Detail View

- [ ] Create individual equipment page
- [ ] Show maintenance history
- [ ] Display room assignments
- [ ] Add status management

4. Room Integration

- [ ] Add equipment tab to room pages
- [ ] Create equipment assignment interface
- [ ] Show equipment status in rooms
- [ ] Implement quick actions

5. Maintenance Management

- [ ] Add maintenance scheduling
- [ ] Create maintenance history tracking
- [ ] Implement maintenance notifications
- [ ] Add maintenance documentation support

**Comment by stewnight** [comment]
RE: the 5th milestone, I implemented this into Jobs, as we previously set up Maintenance as a Job Type.
I expanded on maintenance a little bit more. 
Scheduling works and making a maintenance job from the equipment page.
Recurring jobs isn't yet implemented. Will make a new issue for this
